Repository CVLOG-project/CVL-frontend, pull requests merged in 2023-01, with the labels that each got.

#3 🎉 init: tailwind css plugin and library upload
  package-lock.json
  package.json
  pages/index.tsx
  tailwind.config.js
  yarn.lock
Labels: approve 요청

#5 [LOG-40]✨feat :create responsive mode (navbar)
  components/nav/index.tsx
  pages/_app.tsx
  public/images/github.png
  public/images/notification.png
  public/images/settings.png
Labels: approve 요청, peer review 요청

#7 [LOG-40]✨feat: profile dropdown(navbar)
  components/nav/index.tsx
  public/images/alarm.png
Labels: approve 요청, peer review 요청

#8 [LOG-22]✨feat : ListPage Layout 제작
  components/core/Card/Card.tsx
  package.json
  pages/_app.tsx
  pages/api/axios.ts
  pages/list/index.tsx
  public/mockData/listMockData.json
  yarn.lock
Labels: 완료

#10 ⚰️ remove: dead code & unused file
  .gitignore
  .husky/commit-msg
  commitlint.config.ts
  package-lock.json
  package.json
  yarn.lock
Labels: peer review 요청

#6 [LOG-21]✨feat:create detailpage comment
  components/Comment/comment.tsx
  components/Comment/commentList.tsx
  components/Comment/commentWrite.tsx
  components/Comment/index.tsx
  components/Comment/recomment.tsx
  components/Tag/index.tsx
  components/commentLayout.tsx
  components/nav/Phone.tsx
  pages/_app.tsx
  pages/content/index.tsx
  pages/content/profile.tsx
  pages/test.tsx
  pages/text.tsx
Labels: approve 요청, peer review 요청

#15 [LOG-37]🎨 draft mypage
  pages/mypage/index.tsx
  pages/mypage/profile.tsx
Labels: approve 요청, peer review 요청

#9 [LOG-38]✨feat:make social login(github)
  .gitignore
  components/nav/Alarm.tsx
  components/nav/Phone.tsx
  components/nav/index.tsx
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  public/images/alarm.png
  public/images/more.png
  yarn.lock
Labels: approve 요청, peer review 요청

#13 [LOG-15] ✨feat: implement markdown viewer
  .gitmessage.txt
  .stylelintrc.js
  components/nav/index.tsx
  package.json
  pages/_app.tsx
  pages/post/[pid]/Detail.tsx
  styles/Home.module.css
  styles/markdown.scss
  yarn.lock
Labels: peer review 요청

#17 🚑 hotfix : fix componenet folder
  components/core/nav/Alarm.tsx
  components/core/nav/Phone.tsx
  components/core/nav/index.tsx
  components/domain/Detail/Comment/comment.tsx
  components/domain/Detail/Comment/commentList.tsx
  components/domain/Detail/Comment/commentWrite.tsx
  components/domain/Detail/Comment/index.tsx
  components/domain/Detail/Comment/recomment.tsx
  components/domain/Detail/Tag/index.tsx
  pages/_app.tsx
Labels: approve 요청

#19 [LOG-52]✨ feat: Implement Image Resize Util Function
  package.json
  public/utils/ImageResize.tsx
  yarn.lock
Labels: approve 요청

#18 [LOG-60]✨ feat: SNB레이아웃 구현
  components/core/Card/Card.tsx
  components/core/nav/Alarm.tsx
  components/core/nav/Phone.tsx
  components/domain/Detail/Comment/comment.tsx
  components/domain/Detail/Comment/recomment.tsx
  components/domain/Detail/Tag/index.tsx
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/content/index.tsx
  pages/list/ListView.tsx
  pages/list/SideView.tsx
  pages/list/index.tsx
  public/images/arrow.png
  public/mockData/listMockData.json
Labels: approve 요청, peer review 요청

#16 `[LOG-47]`✨feat: implement markdown code block & table
  package.json
  pages/post/[pid]/Detail.tsx
  styles/markdown.scss
  yarn.lock
Labels: peer review 요청

#20 [LOG-69] 🚑 hotfix: fixed eslint-ignore /children,reactHook
  pages/post/[pid]/Detail.tsx
Labels: approve 요청

#22 [LOG-61]ADD : FOLDER CRUD
  components/domain/List/Folder/CVAddModal.tsx
  components/domain/List/Folder/CVRemoveModal.tsx
  hooks/List.ts
  pages/api/tag/index.ts
  pages/api/tag/type.ts
  pages/list/ListView.tsx
  pages/list/SideView.tsx
  public/images/add.png
  public/images/magnifying-glass.png
  public/images/minus.png
  tailwind.config.js
Labels: approve 요청, peer review 요청
